name: Build release

on:
  release:
    types:
      - published

jobs:
  build_and_publish:
    name: Build executable and attach to release
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' 

      - name: prepare env
        run: |
          python -m pip install --upgrade pip
          python -m pip install pipenv
          python -m pipenv install --system

      - name: build executable
        run: |
          python build.py --create-archive

      - name: attach executable to release
        uses: AButler/upload-release-assets@v2.0.2
        with:
          files: './dist/packed/monokai_pro_keygen_v*.zip;./dist/packed/monokai_pro_keygen_v*.tar.gz'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
