name: Build release

on:
  release:
    types:
      - published

jobs:
  build_and_publish:
    name: Build executable and attach to release
    strategy:
      fail-fast: true
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: prepare env
        run: |
          python -m pip install --upgrade pip
          python -m pip install pipenv
          python -m pipenv install

      - name: build executable
        run: |
          python -m pipenv run python build.py --create-archive

      - name: attach executable to release
        uses: AButler/upload-release-assets@v2.0
        with:
          files: 'dist/packed/*.zip; dist/packed/*.tar.gz'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
